CREATE TABLE Notes (
Code VARCHAR(50) NOT NULL PRIMARY KEY,
Title VARCHAR(100) NOT NULL,
Writer VARCHAR(50) NOT NULL,
Content VARCHAR(MAX) NOT NULL,
Regdate DATE NOT NULL,
Hit INT NOT NULL,
LikeCnt INT NOT NULL
);

SELECT * FROM Notes;